
spring:
  application:
    name: api-gateway 
  cloud:
    config:
      uri:
        - http://localhost:9000  

zuul:
  routes:
    user-service:
      path: /user-service/**
      service-id: user-service
    task-service:
      path: /task-service/**
      service-id: task-service
   ignoredServices: '*'
   host:
      time-to-live: -1
      connect-timeout-millis: 5000
      max-per-route-connections: 10000
      max-total-connections: 5000
      socket-timeout-millis: 60000
   semaphore:
      max-semaphores: 500    
   

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 9090   
      
      
# #timeout
hystrix:
   command:
      default:
         execution:
            iso lation:
               thread:
                  timeoutInMilliseconds: 30000


ribbon:
   ReadTimeout: 60000
   connection-timeout: 3000
   eureka:
      enabled: true


# zuul:
#    ignoredServices: '*'
#    host:
#       time-to-live: -1
#       connect-timeout-millis: 5000
#       max-per-route-connections: 10000
#       max-total-connections: 5000
#       socket-timeout-millis: 60000
#    semaphore:
#       max-semaphores: 500


