spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri:
        - http://localhost:9000

zuul:
  routes:
    user-service:
      path: /user-service/**
      service-id: user-service
    task-service:
      path: /task-service/**
      service-id: task-service

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#timeout
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 100000
ribbon: 
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka: 
    enabled: true
zuul: 
  host: 
    connect-timeout-millis: 100000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore: 
    max-semaphores: 500

