
spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    password: root
    username: root

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update


#Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


server:
  port: 8083   


application:
  version: task-service-v4  
