



spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users
    password: root
    username: root

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update


#task-service:
#  ribbon:
 #   listOfServers: http://localhost:8083/

#Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8082
  
application:
  version: user-service-v4  
  
#Logger
logging:
  level:
    com.microservice: info
  file:
    name: logs/elk_logs.log
  
  

# #timeout
# hystrix: 
#   command: 
#     default: 
#       execution: 
#         isolation: 
#           thread: 
#             timeoutInMilliseconds: 100000
# ribbon: 
#   ReadTimeout: 60000
#   connection-timeout: 3000
#   eureka: 
#     enabled: true
# zuul: 
#   host: 
#     connect-timeout-millis: 100000
#     max-per-route-connections: 10000
#     max-total-connections: 5000
#     socket-timeout-millis: 60000
#   semaphore: 
#     max-semaphores: 500  
